In [ ]:
import numpy as np

# Создание массива из списка
arr1 = np.array([1, 2, 3, 4, 5])
print("Массив из списка:", arr1)

# Создание массива с помощью arange (аналог range)
arr2 = np.arange(0, 10, 2)  # от 0 до 10 с шагом 2
print("Массив с помощью arange:", arr2)

# Создание массива из нулей
zeros_arr = np.zeros(5)
print("Массив из нулей:", zeros_arr)

# Создание массива из единиц
ones_arr = np.ones(5)
print("Массив из единиц:", ones_arr)

# Создание массива со случайными числами
random_arr = np.random.rand(5)
print("Массив случайных чисел:", random_arr)


# Создание двумерного массива
matrix = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])
print("Двумерный массив 3x3:")
print(matrix)

# Индексирование двумерного массива
print("\nЭлемент в строке 1, столбце 2:", matrix[1, 2])  # 6
print("Вторая строка:", matrix[1, :])  # [4, 5, 6]
print("Первый столбец:", matrix[:, 0])  # [1, 4, 7]

# Срезы в двумерном массиве
print("\nПодматрица (первые 2 строки, последние 2 столбца):")
print(matrix[:2, 1:])



# Базовые арифметические операции
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

print("Массив a:", a)
print("Массив b:", b)
print("a + b =", a + b)  # поэлементное сложение
print("a * 2 =", a * 2)  # умножение на скаляр
print("a * b =", a * b)  # поэлементное умножение

# Математические функции
print("\nМатематические операции:")
print("sin(a) =", np.sin(a))
print("квадратный корень a =", np.sqrt(a))
print("сумма всех элементов a =", np.sum(a))
print("среднее значение a =", np.mean(a))

# Операции с двумерным массивом
print("\nОперации с матрицей:")
print("Сумма по столбцам:", np.sum(matrix, axis=0))
print("Сумма по строкам:", np.sum(matrix, axis=1))
print("Транспонированная матрица:")
print(matrix.T)


# Создание массива и фильтрация
data = np.array([10, 25, 3, 18, 7, 30, 12])
print("Исходный массив:", data)

# Фильтрация элементов больше 15
filtered = data[data > 15]
print("Элементы больше 15:", filtered)

# Замена элементов по условию
data[data < 5] = 0
print("Массив после замены (<5 на 0):", data)

Массив из списка: [1 2 3 4 5]
Массив с помощью arange: [0 2 4 6 8]
Массив из нулей: [0. 0. 0. 0. 0.]
Массив из единиц: [1. 1. 1. 1. 1.]
Массив случайных чисел: [0.97735566 0.51899534 0.86449146 0.51738967 0.47894015]
Двумерный массив 3x3:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Элемент в строке 1, столбце 2: 6
Вторая строка: [4 5 6]
Первый столбец: [1 4 7]

Подматрица (первые 2 строки, последние 2 столбца):
[[2 3]
 [5 6]]
Массив a: [1 2 3 4]
Массив b: [5 6 7 8]
a + b = [ 6  8 10 12]
a * 2 = [2 4 6 8]
a * b = [ 5 12 21 32]

Математические операции:
sin(a) = [ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
квадратный корень a = [1.         1.41421356 1.73205081 2.        ]
сумма всех элементов a = 10
среднее значение a = 2.5

Операции с матрицей:
Сумма по столбцам: [12 15 18]
Сумма по строкам: [ 6 15 24]
Транспонированная матрица:
[[1 4 7]
 [2 5 8]
 [3 6 9]]
Исходный массив: [10 25  3 18  7 30 12]
Элементы больше 15: [25 18 30]
Массив после замены (<10 на 0): [10 25  0 18  7 30 12]
